# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "axe-0.8.0-M2JU5SuRAABRUbICFInh_GltUm46JBd986HQCE7j6BJz";
    path = fetchgit {
      url = "https://github.com/Ratakor/axe";
      rev = "186078c497e4e4dab20926c1b135fa9ab8a6a3b1";
      hash = "sha256-DV4yH43OBzmeLTRZXRWVn8r+TEI22u4bmhdr4nLg+4U=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk7q6AgBdMJxze3D4l9ylQhkviQ_BX9FigDt13MFn";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "2a79678e05e4e82cd4efd4fd6b754dcf029c3a64";
      hash = "sha256-LFNg8yu82OcQ+Yyxw1bTotjW18oVhNiYrFGIE/7WWR4=";
    };
  }
]
