# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
  fetchgit,
}:
linkFarm "zig-packages" [
  {
    name = "axe-0.7.0-M2JU5cyPAADJQcWDZE7xNmnuQtAgwmPLyCMjiLhOptrC";
    path = fetchgit {
      url = "https://github.com/Ratakor/axe";
      rev = "4df48b5fd1bd8496dc3a9ed49790649b7c4e8fee";
      hash = "sha256-4sfZrg1pyabA6tRuapscZAWFYEM7vjpMy6wuZgLYIcY=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk0J9AgCVa0nnyL0lNY9Xa9F68hHq-ZarhuXNV-Jb";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit";
      rev = "ed2ca60db118414bda2b12df2039e33bad3b0b88";
      hash = "sha256-IvXaqAzaWi3E1XBqQltCBFoRmXehZkVol3/RZwOsAKg=";
    };
  }
]
