# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "axe-0.8.0-M2JU5TSRAADWArXWoguF9hbnO-BX02rG3iFeyItCBKej";
    path = fetchgit {
      url = "https://github.com/Ratakor/axe";
      rev = "4492b8401f603f8444620b0b5bb039cdb312049b";
      hash = "sha256-fCif5nKLbS4v0uZ/TZdyEL8Tqkq0Fvhpl5pJnhXr+4c=";
    };
  }
  {
    name = "zeit-0.6.0-5I6bk3K6AgCFnc_9CN7KJjaeNJz1VuwP4DA7Gs9vgxuz";
    path = fetchgit {
      url = "https://github.com/rockorager/zeit?ref=0.16";
      rev = "fdaad9c5884f41a3640c768f4f9fc116e763c321";
      hash = "sha256-LFNg8yu82OcQ+Yyxw1bTotjW18oVhNiYrFGIE/7WWR4=";
    };
  }
]
